import Head from 'next/head'
import Image from 'next/image'
// import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'
import { useState } from 'react'

// const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [user, setUser] = useState('ndr')

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h4>LANDING</h4>
        <div style={{ display: 'inline-block' }}>
          <span style={{ marginRight: 5 }}>User</span>
          <select onChange={(e) => setUser(e.target.value)} style={{ marginRight: 5 }}>
            {/* <option value=''><em>None</em></option> */}
            <option value='ndr'>ndr</option>
            <option value='xixixviii'>xixixviii</option>
            <option value='Lisundawu'>Lisundawu</option>
            <option value='Nadifa'>Nadifa</option>
          </select>
          <Link href={`/user/${user}`}>
            <button>Go To User Page</button>
          </Link>
        </div>
        <Link href={`/todos`}>
          <button>Go To SSR Page</button>
        </Link>
        <Link href={`/todo-get-api-next`}>
          <button>Go To SSR Page With Get API from Local Next Js</button>
        </Link>
        <Link href={`/todo-ssg`}>
          <button>Go To SSG Page</button>
        </Link>
        <Link href={`/todo-csr`}>
          <button>Go To CSR Page with React-Query</button>
        </Link>
        <Link href={`/todo-csr-no-rq`}>
          <button>Go To CSR Page without React-Query</button>
        </Link>
      </main>
    </>
  )
}
